"""Switch to MySQL

Revision ID: 90bb148c0141
Revises: 
Create Date: 2025-12-01 14:02:57.886821

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90bb148c0141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crud_tbl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crud_tbl',
    sa.Column('ct_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('some_string', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('some_text', mysql.TEXT(), nullable=True),
    sa.Column('some_int', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dtg', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('ct_id')
    )
    # ### end Alembic commands ###
